package br.com.planned.api.entity;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * A task ({@code TASK}). Tasks form a tree through {@code PARENT_TASK_ID} (PLAN §0, Subtasks):
 * a top-level task has no parent. The owner and the parent are set at creation and never change,
 * so they have no setters.
 *
 * <p>There is deliberately no {@code children} collection: deleting a task relies on the
 * database's {@code ON DELETE CASCADE} to remove the subtree (wave 2, D1), and subtasks are
 * loaded by query. {@code createdAt} and {@code updatedAt} come from the injected {@code Clock}.
 */
@Entity
@Table(name = "task")
@Getter
@Setter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Task {

	/** Generated by the application (Hibernate) on persist, not by the database. */
	@Id
	@GeneratedValue(strategy = GenerationType.UUID)
	@Setter(AccessLevel.NONE)
	private UUID id;

	@Column(nullable = false, length = 100)
	private String title;

	@Column(nullable = false, length = 500)
	private String description;

	/** A date with no time component; "today" comes from {@code app.timezone} (PLAN §0). */
	@Column(name = "due_date")
	private LocalDate dueDate;

	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "user_id", nullable = false, updatable = false)
	@Setter(AccessLevel.NONE)
	private User user;

	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "priority_id", nullable = false)
	private Priority priority;

	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "status_id", nullable = false)
	private TaskStatus status;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "complexity_id")
	private Complexity complexity;

	/** {@code null} for a top-level task. */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_task_id", updatable = false)
	@Setter(AccessLevel.NONE)
	private Task parent;

	/** Order among its siblings (wave 2, D5). Internal: never exposed by the API. */
	@Column(nullable = false)
	private int position;

	@Column(name = "created_at", nullable = false, updatable = false)
	@Setter(AccessLevel.NONE)
	private Instant createdAt;

	@Column(name = "updated_at", nullable = false)
	private Instant updatedAt;

	/**
	 * @param parent {@code null} for a top-level task; a subtask must have its parent's user
	 */
	public Task(User user, Task parent, String title, String description, Priority priority, TaskStatus status,
			Instant createdAt) {
		this.user = user;
		this.parent = parent;
		this.title = title;
		this.description = description;
		this.priority = priority;
		this.status = status;
		this.createdAt = createdAt;
		this.updatedAt = createdAt;
	}
}
