CREATE TABLE PRIORITIES (
   ID   SERIAL      PRIMARY KEY,
   NAME VARCHAR(50) NOT NULL UNIQUE CHECK (NAME ~ '\S')
);

CREATE TABLE TASK_STATUS (
   ID   SERIAL      PRIMARY KEY,
   NAME VARCHAR(50) NOT NULL UNIQUE CHECK (NAME ~ '\S')
);

CREATE TABLE COMPLEXITIES (
   ID   SERIAL      PRIMARY KEY,
   NAME VARCHAR(50) NOT NULL UNIQUE CHECK (NAME ~ '\S')
);

CREATE TABLE ROLE (
   ID   SERIAL      PRIMARY KEY,
   NAME VARCHAR(50) NOT NULL UNIQUE CHECK (NAME ~ '\S')
);

CREATE TABLE USERS (
   ID         UUID         PRIMARY KEY,
   NAME       VARCHAR(100) NOT NULL CHECK (NAME ~ '\S'),
   EMAIL      VARCHAR(100) NOT NULL UNIQUE CHECK (EMAIL ~ '\S'),
   PASSWORD   VARCHAR(100) NOT NULL CHECK (PASSWORD ~ '\S'),
   ROLE_ID    INT          NOT NULL REFERENCES ROLE(ID),
   CREATED_AT TIMESTAMP    NOT NULL,
   UPDATED_AT TIMESTAMP    NOT NULL CHECK (UPDATED_AT >= CREATED_AT)
);

CREATE TABLE TASK (
   ID            UUID         PRIMARY KEY,
   USER_ID       UUID         REFERENCES USERS(ID),
   TITLE         VARCHAR(100) NOT NULL,
   DESCRIPTION   VARCHAR(500) NOT NULL CHECK (DESCRIPTION ~ '\S'),
   PRIORITY_ID   INT          REFERENCES PRIORITIES(ID),
   STATUS_ID     INT          REFERENCES TASK_STATUS(ID),
   COMPLEXITY_ID INT          REFERENCES COMPLEXITIES(ID),
   CREATED_AT    TIMESTAMP    NOT NULL,
   UPDATED_AT    TIMESTAMP    NOT NULL CHECK (UPDATED_AT >= CREATED_AT)
);

CREATE TABLE TASK_SUBTASK (
   PARENT_TASK_ID UUID REFERENCES TASK(ID) ON DELETE CASCADE,
   SUBTASK_ID     UUID REFERENCES TASK(ID) ON DELETE CASCADE,
   CONSTRAINT PK_TASK_SUBTASK PRIMARY KEY (PARENT_TASK_ID, SUBTASK_ID)
);

INSERT INTO PRIORITIES (NAME) VALUES ('LOW');
INSERT INTO PRIORITIES (NAME) VALUES ('MEDIUM');
INSERT INTO PRIORITIES (NAME) VALUES ('HIGH');

INSERT INTO TASK_STATUS (NAME) VALUES ('TODO');
INSERT INTO TASK_STATUS (NAME) VALUES ('IN_PROGRESS');
INSERT INTO TASK_STATUS (NAME) VALUES ('OVERDUE');
INSERT INTO TASK_STATUS (NAME) VALUES ('DONE');

INSERT INTO COMPLEXITIES (NAME) VALUES ('EASY');
INSERT INTO COMPLEXITIES (NAME) VALUES ('MEDIUM');
INSERT INTO COMPLEXITIES (NAME) VALUES ('HARD');

INSERT INTO ROLE (NAME) VALUES ('USER');
INSERT INTO ROLE (NAME) VALUES ('ADMIN');