-- Task schema for Wave 2 (PLAN §1, wave 2 D1 and D5).
-- TASK_SUBTASK is empty: no endpoint wrote tasks before this migration.
DROP TABLE TASK_SUBTASK;

ALTER TABLE TASK
   ADD COLUMN DUE_DATE DATE NULL,
   ADD COLUMN PARENT_TASK_ID UUID NULL REFERENCES TASK(ID) ON DELETE CASCADE,
   -- Keeps the order subtasks were created in. Internal: never exposed by the API.
   ADD COLUMN POSITION INT NOT NULL DEFAULT 0,
   ADD CONSTRAINT CK_TASK_TITLE_NOT_BLANK CHECK (TITLE ~ '\S'),
   ADD CONSTRAINT CK_TASK_NOT_OWN_PARENT CHECK (PARENT_TASK_ID <> ID),
   ALTER COLUMN USER_ID SET NOT NULL,
   ALTER COLUMN STATUS_ID SET NOT NULL,
   ALTER COLUMN PRIORITY_ID SET NOT NULL;

CREATE INDEX IX_TASK_PARENT_TASK_ID ON TASK (PARENT_TASK_ID);
CREATE INDEX IX_TASK_USER_STATUS_DUE_DATE ON TASK (USER_ID, STATUS_ID, DUE_DATE);
