-- Estimated effort in whole hours (wave 4, D10). NULL means not estimated.
ALTER TABLE TASK
   ADD COLUMN ESTIMATED_HOURS INT NULL,
   ADD CONSTRAINT CK_TASK_ESTIMATED_HOURS_RANGE CHECK (ESTIMATED_HOURS BETWEEN 1 AND 999);
