spring.application.name=Planned-AI-Task-Manager
server.port=8080

# Database configuration
spring.datasource.url=${TASK_MANAGER_DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

flyway.enabled=true
flyway.locations=classpath:db/migration/postgres
flyway.url=${TASK_MANAGER_DB_URL}
flyway.user=${POSTGRES_USER}
flyway.password=${POSTGRES_PASSWORD}

# Spring Security
jwt.secret=${JWT_SECRET}

# Gemini API key
gemini.api.key=${GEMINI_API_KEY}
gemini.model=${GEMINI_MODEL}